tunnel: 8ff00a2d-38a5-4ab1-a2f3-7e99e29760d2
credentials-file: C:\Users\pache\.cloudflared\8ff00a2d-38a5-4ab1-a2f3-7e99e29760d2.json

ingress:
  - hostname: front.plataformaeducativa.store
    service: http://localhost:3000
  - hostname: api.plataformaeducativa.store
    service: http://localhost:5000
  - service: http_status:404